### ISSUE TITLE
can i install without qiime2 in windows

### ISSUE THREAD

**Issue by khemlalnirmalkar** [sbslee/dokdo#23]
Hi @sbslee 
Is it possible to use dokdo through Jupyter notebook in windows without qiime2? 
Sorry, if I missed something in your documentation section.
Thanks,

**Comment by sbslee** [comment]
@khemlalnirmalkar,

Unfortunately, Dokdo must be run in an environment where QIIME 2 is already installed because Dokdo uses QIIME 2 API extensively. May I ask why you're asking the question? Maybe I can still help.

**Comment by khemlalnirmalkar** [comment]
@sbslee,
I just wanted to avoid switching windows to linux or use a workstation.

**Comment by sbslee** [comment]
@khemlalnirmalkar,

Got it. If that's the case, there isn't much I can do to help :( Sorry!

**Comment by khemlalnirmalkar** [comment]
@sbslee no worries, thanks for the quick response,
