### ISSUE TITLE
dokdo summarize error

### ISSUE THREAD

**Issue by JetbluejetYJ** [sbslee/dokdo#29]
Hello, I'm hosting a microbiome study these days. Currently, I am learning a lot and feeling grateful through a program called 'dokdo'. This is a wonderful kackage! In the process of performing dokdo pipeline, if you look at the 6th item (6. Summarize and Filter ASV Table), A parameter error occurs in the code of 'dokdo summarize table.qza'. You will be busy with a lot of research, but please check. Thanks. (I think the parameter item is missing, for example -i?)
![제목 없음](https://user-images.githubusercontent.com/91312133/135398269-514cff41-2d02-42fe-9cdc-38b617cf8914.png)

**Comment by sbslee** [comment]
Thanks for reporting the typo! It's been fixed in e0d0683.
