### ISSUE TITLE
dokdo beta_parallel_plot issue

### ISSUE THREAD

**Issue by JetbluejetYJ** [sbslee/dokdo#41]
안녕하세요, dokdo를 사용하고 있고 많이 배워가고 있는 새내기 과학자입니다.
dokdo에서 `beta_parallel_plot` 을 사용하여 2개의 axis에 plot을 그려보려고 했으나 Warning이 발생하여 문의드립니다.
2개의 ax1, ax2를 그리고, 각각 plot을 그리려고 했지만 한곳에 모두 그려지는 현상을 발견했습니다.
각종연구로 인해 많이 바쁘시겠지만 확인부탁드립니다 :)

```
/00.Qiime2/dokdo/dokdo/api/beta_parallel_plot.py:121: UserWarning: FixedFormatter should only be used together with FixedLocator
  ax.set_xticklabels(props)
```

**Comment by sbslee** [comment]
Fixed in 836410a
