### ISSUE TITLE
taxa_abundance_bar_plot issue

### ISSUE THREAD

**Issue by JetbluejetYJ** [sbslee/dokdo#43]
안녕하세요 @sbslee 
dokdo API들 중, taxa_abundance_bar_plot 관련 문의 드립니다.

다양한 parameter들 중에서 sample 이름으로만 제거하거나 혹은 keep할 수 있는 option이 없는데
혹시 추가 가능하실까요?

각종 연구로 많이 바쁘실텐데 항상 도움 주셔서 감사합니다.

**Comment by sbslee** [comment]
There's already an option in the `taxa_abundance_bar_plot` method called `sample_names` that you can use to select which samples to display. Closing this.
