### ISSUE TITLE
exclude "others" from relative abundance and plot

### ISSUE THREAD

**Issue by khemlalnirmalkar** [sbslee/dokdo#45]
Hi @sbslee 
1. How can i remove "others" from the relative abundance bar-plot and plot the rest of them?
I understand that bar plot will not be 100%.
2. If you see the attached image, the order of colors in bars (e.g. orange at the bottom) and legends (orange on top) are almost in opposite directions. How can I keep both of them in the same order?

Thanks

![image](https://user-images.githubusercontent.com/32944151/182226787-81629e65-4c2a-4a0d-a10d-dea24d133231.png)

**Comment by mishkb** [comment]
Hi @khemlalnirmalkar 

To not show the Others in the taxa abundance bar plot - use the flag `show_others=False` (it is True by default). Use the same flag in the plot for the legend if you are building the figure as 2 plots (bar plot and legend).

To reverse the order of the legend - the code below worked for me as @sbslee details in this closed issue: 
https://github.com/sbslee/dokdo/issues/26#issuecomment-909760867

This assumes you display the stacked bar chart with no legend and the legend only in the second plot
```
handles, labels = ax2.get_legend_handles_labels()
ax2.legend(handles[::-1], labels[::-1])
```
I had the same questions previously :-)

**Comment by sbslee** [comment]
@mishkb, I cannot say thank you enough for your post! Not only your answer is right on the spot, it is also concise and fully backed :) Really appreciate your help.

@khemlalnirmalkar, please let me know if you have additional questions!

**Comment by khemlalnirmalkar** [comment]
Hi @mishkb Thank you so much for your help,
I was able to resolve my both queries,
Cheers
